//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataType
    {
        public int DataTypeId { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Created { get; set; }
    }
}
